
resolver: nightly-2022-01-15

packages:
- .

extra-deps:
- git: https://github.com/codedownio/lsp.git
  commit: a97a2ec822d77a24cfb6278c3f024598265844f9
  # nix-sha256: 0hqpj3lndglg5853yv32ys1jr6nhfzljxnr73fxs4s22qfrfin97
  subdirs:
  - lsp-types
